name: Selenium Test
on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Selenium Tests
        run: mvn test

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results

  generate-report:
    runs-on: ubuntu-latest
    
    needs: run-tests
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Allure Results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Download allure .deb package and install it.
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure_2.18.1-1_all.deb
          sudo dpkg -i allure_2.18.1-1_all.deb

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o build/allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: build/allure-report

  deploy-reports:
    needs: generate-report
    
    permissions:
      contents: write
      pages: write     
      id-token: write
      
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'

      - name: Download Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: build/allure-report

      - name: configure github pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      - name: upload atrifacts
        uses: actions/upload-pages-artifact@v1
        with: 
          path: "./build/allure-report"

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
